### ISSUE TITLE
crashes after opening the browser

### ISSUE THREAD

**Issue by wizzard0** [fireproof-storage/firehouse-chat#9]
repro:

- npm i
- npm run dev
- open http://127.0.0.1:1999

```
firehouse-chat/node_modules/partykit/dist/bin.mjs:96377
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "strategy" argument must be of type object. Received type number (0)
    at new ReadableStream (node:internal/webstreams/readablestream:253:5)
    at safeReadableStreamFrom (firehouse-chat/node_modules/miniflare/dist/src/index.js:7975:10)
    at #handleLoopback (firehouse-chat/node_modules/miniflare/dist/src/index.js:8137:36)
    at Server.emit (node:events:531:35)
    at parserOnIncoming (node:_http_server:1150:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v22.9.0

Process finished with exit code 7
```

**Comment by wizzard0** [comment]
tried to update all fireproof deps, now `npm run dev` crashes immediately:

```
partykit dev --live
🎈 PartyKit v0.0.111
---------------------
Loading environment variables from ../../../.env
ConfigurationError: Could not find party: node_modules/@fireproof/partykit/src/server.ts
    at getConfig (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:84332:15)
    at file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:92952:11
    at Object.lf [as useState] (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:8493:43)
    at exports2.useState (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:307:24)
    at useDev (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:92951:48)
    at DevImpl (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:92797:43)
    at Re (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:8327:14)
    at bi (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:11107:17)
    at ai (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:10803:17)
    at $h (file:///firehouse-chat/node_modules/partykit/dist/bin.mjs:10797:30)
✘ [ERROR] Could not find party: node_modules/@fireproof/partykit/src/server.ts
```
